# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  resources: !include lovelace/other/resources.yaml
homeassistant:
  packages: !include_dir_named packages
  external_url: "https://yourdomain.duckdns.org:8123"
  internal_url: "http://192.168.1.123:8123"
  media_dirs:
    media: /config/www/music

frontend:
  javascript_version: latest


